### ISSUE TITLE
File Picker creates need to include NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by chillbrodev** [codegrue/flutter_material_pickers#11]
I really dig this package as it creates nice pickers. However, it causes me to include the NSPhotoLibraryUsageDescription for iOS in my application, and well it seems unnecessary. Are you able to split out the material file picker into its own package?

**Comment by codegrue** [comment]
It's even more integrated now in the 2.0 version unfortunently

**Comment by chillbrodev** [comment]
If anything you should make this known in the documentation
