### ISSUE TITLE
A problem occurred configuring project ':file_picker'.

### ISSUE THREAD

**Issue by WijdanMTak** [codegrue/flutter_material_pickers#12]
Hello,
whenI added your plugin the build failed for some reason.
can you please help me to figure out what is the problem!
I will provide you some info that may help you:
**android/build.gradle:**
`
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
`   

**app/build.gradle:**

`
compileSdkVersion 29
targetSdkVersion 29
`

details of the error is as follows:

> FAILURE:` Build failed with an exception.

> *` What went wrong:

> A problem occurred configuring project ':file_picker'.

> > Could not resolve all artifacts for configuration ':file_picker:classpath'.

   

> > Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).

     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar
> Failed to notify project evaluation listener.

   > Could not get unknown property 'android' for project ':file_picker' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type 

> org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

> * Try:

> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 

> get full insights.

> * Get more help at https://help.gradle.org

> BUILD FAILED in 582ms

> Finished with error: Gradle task assembleDebug failed with exit code 1 

`

**Comment by codegrue** [comment]
Does it build fine for iOS?

**Comment by WijdanMTak** [comment]
Actually, I haven't tried yet, now I just build for android.
but I will start the test at the end of this week, and I will let you know with the results

**Comment by codegrue** [comment]
Upgraded it to use file_picker 2.0 and tested on iOS, Android, and Web.

**Comment by MICKNICK911** [comment]
i am facing the same with no solution yet

**Comment by codegrue** [comment]
The file_picker is an included library. Try to get your project to build just with that to see if the incompatibility is there.

**Comment by MICKNICK911** [comment]
please can you show me a sample code on how to  implement the included library.
I am really having a hard time going about it

**Comment by codegrue** [comment]
The project includes a sample app in the Example folder.
