### ISSUE TITLE
Execution failed for task ':app:mergeDebugAssets' when building embedded file_picker

### ISSUE THREAD

**Issue by DaniEid** [codegrue/flutter_material_pickers#13]
i have a project that uses flutter_material_picker and i'm using the latest version   flutter_material_pickers: ^1.7.4.
when trying to run the application on any device i got the following error from file_picker 
What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find fragment-1.1.0.aar (androidx.fragment:fragment:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.aar
   > Could not find viewpager-1.0.0.aar (androidx.viewpager:viewpager:1.0.0).
     ..... etc 
then i got the following :
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin file_picker.. 
and this also fails 
C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:10: error: cannot find symbol
import androidx.lifecycle.DefaultLifecycleObserver;
                         ^
  symbol:   class DefaultLifecycleObserver
  location: package androidx.lifecycle
C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:20: error: cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
 symbol:   class DefaultLifecycleObserver
  location: class FilePickerPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:45: error: method does not override or implement a method from a supertype
        @Override
        ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:49: error: method does not override or implement a method from a supertype
        @Override
        ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:53: error: method does not override or implement a method from a supertype
        @Override
        ^C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:57: error: method does not override or implement a method from a supertype
  C:\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.13.3\android\src\main\java\com\mr\flutter\plugin\filepicker\FileUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

noting that the file_picker within material_picker is outdated (used version 1.13.3, available version ^2.0.0)
and i'm using Flutter 1.20.4 • channel stable
Tools • Dart 2.9.2

**Comment by codegrue** [comment]
Updated file_picker. Please reopen if that didn't fix the problem
