### ISSUE TITLE
Feature request: Ability to split label and value on scrollpicker

### ISSUE THREAD

**Issue by avrelaun** [codegrue/flutter_material_pickers#15]
The scrollpicker is currently taking a list of Strings as items parameter.

I have a use case where I'd like to pass a list of objects as items and specify which object property to use as label (showing in the list), but when selected the returning value would be another object property.

Here's what the show function call might look like:

```
showSplitScrollPicker(
context: context,
title: 'my split scrollpicker',
items: [{
 id: 1,
 label: 'first item',
 whatever: 'bla'
},{
 id: 2,
 label: 'second',
 whatever: 'bla 2'
},{
 id: 3,
 label: 'third',
 whatever: 'bla 3'
}],
itemLabel: 'label',
itemValue: 'id'
)
```

**Comment by codegrue** [comment]
I agree this is a needed change for all the list type pickers. It's a breaking change so will need to go into the 2.0 version.

**Comment by gbaccetta** [comment]
Hello there, thanks for the hard work! Do you plan to add this feature in a future release ?
If I want to show localized String, conversion back and forth can become tricky without a fixed value being exchanged.

**Comment by codegrue** [comment]
What if I add an optional "values" collection? That way it won't be a breaking change.

**Comment by gbaccetta** [comment]
Yes that could be a good solution. 

Although to do not break it I think it should still be a String list, and if a value List is provided, the variable returned as picked value, is the String from the value array instead of the String from the items array. 

A breaking change could have two values returned, both the value and item. 

Another possibility could be a new type of picker altogether because you do not need this when using a numeric, date or color picker. You only need this when using String or Icon + String in my opinion... Although that may not be true for everyone.

**Comment by codegrue** [comment]
Feature added to 2.1.0

**Comment by tehsphinx** [comment]
Isn't the whole point of the values/items separation that the user never sees the values, but only the items (labels)?

Unfortunately now it shows the values instead of the items if provided. It should instead _show_ the items and _use_ the values as `selectedValue`.

**Comment by codegrue** [comment]
No it shows the items in the pickers. The sample app is displaying the returned values, but that's outside the library.

**Comment by elliotrtd** [comment]
But it doesn't show the item in the picker? 

In your example MaterialScrollPicker shows the State Abbreviations in the Picker as well which is the list of values, not items, and it's the same in my application. 

The Text widget for each item uses the value variable, which is called from values. The items are not shown anywhere, unless we're both totally missing something?

**Comment by tehsphinx** [comment]
> No it shows the items in the pickers.

It doesn't.

**Comment by tehsphinx** [comment]
To elaborate: Completely agree with your statement @codegrue. Only problem is that it does not behave as you described.

**Comment by codegrue** [comment]
Can you post some screen shots? The example app behaves as I describe to me.

**Comment by codegrue** [comment]
Fixed in 2.1.1. Sorry this was a lack of regression testing bug. Thanks for raising it and for the PR.

**Comment by tehsphinx** [comment]
Thx @codegrue

**Comment by elliotrtd** [comment]
Thanks for the super quick fix!

**Comment by gbaccetta** [comment]
Yes thank you,

That works great.
