### ISSUE TITLE
Validator Form

### ISSUE THREAD

**Issue by sokunsamnang** [codegrue/flutter_material_pickers#16]
How can I get validation this material picker ?? Example, I customize date picker as DOB picker and valueText: _birthdate ?? 'Select Date of Birth'. So, if user not select this button to set value, it have to validated.

**Comment by codegrue** [comment]
This library returns onChanged which you can use to consume or analyze the returned values. If you want a validate method like in flutter forms, that is on the form field widget, and is out of scope for the intent of this library, which is to display the dialogs. Check out `Card Settings` for an example of this being used to create form fields.
