### ISSUE TITLE
error when update package intl 0.17.0

### ISSUE THREAD

**Issue by tuemaytinh1981** [codegrue/flutter_material_pickers#24]
Because flutter_material_pickers >=1.9.2 depends on intl >=0.16.0 <=0.17.0-nullsafety.2 and waitingwork depends on intl ^0.17.0, flutter_material_pickers >=1.9.2 is forbidden.
So, because waitingwork depends on flutter_material_pickers ^1.9.2, version solving failed.
pub get failed (1; So, because waitingwork depends on flutter_material_pickers ^1.9.2, version solving failed.)
Process finished with exit code 1

Thanks.

**Comment by Joseph-Nathan** [comment]
please help .

**Comment by 6h4n3m** [comment]
#26 should fix this issue, this is happening because one of your packages depends on the stable null safe version of the intl package and v1.9.2 is not null safe.

The update is not on Pub yet, cc @codegrue can tell you when to expect the package itself to be updated on Pub.

**Comment by codegrue** [comment]
This was fixed a few weeks back.
