### ISSUE TITLE
Allow changing the bottom buttons text and onpressed

### ISSUE THREAD

**Issue by fernando-s97** [codegrue/flutter_material_pickers#3]
It would be nice if we could change the bottom buttons text and pass our own click handler (at least in showMaterialResponsiveDialog)

**Comment by codegrue** [comment]
You do pass a click handler for OK. Do you need one for Cancel also?

**Comment by fernando-s97** [comment]
Supposing the scenario where I could change the text of the Cancel button (which means it would represent another action), it would be necessary to also have a custom callback

**Comment by codegrue** [comment]
label text fixed on v1.6.0. For the cancel callback, do you just need to know it was pressed?

**Comment by codegrue** [comment]
Added onCancelled handler in v1.6.0 also.
