### ISSUE TITLE
Error with flutter_colorpicker after installing dependencies 

### ISSUE THREAD

**Issue by cutenesss** [codegrue/flutter_material_pickers#32]
i got this error after installing. can you look into it?

/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/D:/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/D:/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

**Comment by cutenesss** [comment]
Duplicate of #30 
Nevermind, i just notice that you are working on it already. gonna close this now. but have you finished?

**Comment by codegrue** [comment]
3.1.2 deployed to address this
