### ISSUE TITLE
Flutter 2.5.0 - Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'

### ISSUE THREAD

**Issue by NikolaGrujic91** [codegrue/flutter_material_pickers#36]
After updating to Flutter 2.5.0 error started showing up.

Launching lib/main.dart on macOS in debug mode...
Building macOS application...
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../Developer/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../Developer/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^

Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
** BUILD FAILED **

Exception: Build process failed

flutter --version
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (13 hours ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

**Comment by elhe26** [comment]
I'm having the same problem.

**Comment by eae1212** [comment]
I also have the same problem. After downgrade to 2.2.3 build is ok

**Comment by bobatsar** [comment]
Flutter colorpicker has released an updated version with a fix.
See https://github.com/mchome/flutter_colorpicker/issues/56

Can you please update the dependency to use `flutter_colorpicker 0.6.0`?

Current workaround in `pubspec.yaml`

```
dependency_overrides:
  flutter_colorpicker: ^0.6.0 
```

**Comment by NikolaGrujic91** [comment]
Workaround suggested by @bobatsar solved the error in my case. Thanks!
