### ISSUE TITLE
CardSettingsListPicker : ScrollPicker shows a divider that cuts focused item in half

### ISSUE THREAD

**Issue by celariss** [codegrue/flutter_material_pickers#56]
To begin, thank you for your wonderful library :)

In CardSettingsListPicker, when the user wants to change the selected value, a ScrollPicker is shown with "showDivider" property set to true (default), resulting in an ugly line that cuts the selected value in half.

I have this issue in Web, Desktop and Android envs.

Image of the issue :
![image](https://github.com/codegrue/flutter_material_pickers/assets/39798615/aece8287-1962-471e-bc51-94d6b15336fd)

The problem is fixed by providing "showDivider=false" in card_settings_list_picker.dart, line 151 :
```dart
 void _showMaterialScrollPicker(String label, T? selectedItem) {
    showMaterialScrollPicker<T?>(
      context: context,
      title: label,
      items: items,
      showDivider: false, // <= here is the new line
      selectedItem: selectedItem,
      onChanged: (value) {
        didChange(value);
        if (widget.onChanged != null) widget.onChanged!(value);
      },
    );
```

Image with the fix :
![image](https://github.com/codegrue/flutter_material_pickers/assets/39798615/9a27fa19-1f73-4a3b-9cb1-624b22673730)

Far better ;)

I didn't find any solution that does not need at least a change in flutter_material_pickers code ...

**Comment by codegrue** [comment]
This will be fixed on 3.7.0
