### ISSUE TITLE
Problem on version 1.7.2

### ISSUE THREAD

**Issue by gustavomesquita** [codegrue/flutter_material_pickers#9]
First of all, congratulations for the great plugin.

I found a problem that happens only on version 1.7.2 when using functions **showMaterialScrollPicker** and **showMaterialNumberPicker**.

On previous versions that problem doesn't occurs.
![ScrollPicker](https://user-images.githubusercontent.com/18652205/91250927-8b50db80-e730-11ea-8836-89a4e34985c4.png)
![Number Picker](https://user-images.githubusercontent.com/18652205/91250947-9ad02480-e730-11ea-9136-6e6469fa7694.png)

**Below you can see the error description from flutter terminal:**

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LayoutBuilder:
flutter: Failed assertion: boolean expression must not be null
flutter:
flutter: The relevant error-causing widget was:
flutter:   LayoutBuilder
flutter:   file:///Users/macdev/Devtools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_material_pickers-1.7.2/lib/pickers/scroll_picker.dart:62:12
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _ScrollPickerState.build.<anonymous closure> (package:flutter_material_pickers/pickers/scroll_picker.dart:92:34)
flutter: #1      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:121:33)
flutter: #2      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
flutter: #3      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:117:11)
flutter: #4      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1868:58)
flutter: #5      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:920:15)
flutter: #6      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1868:13)
flutter: #7      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:226:7)
flutter: #8      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:299:5)
flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #10     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:827:17)
flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #12     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:301:13)
flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #14     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #21     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
flutter: #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #23     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
flutter: #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #25     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:396:13)
flutter: #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #27     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
flutter: #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #29     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
flutter: #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #44     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:13)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #48     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
flutter: #49     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
flutter: #50     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
flutter: #51     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #52     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #53     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #54     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #55     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #56     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #60     _invoke (dart:ui/hooks.dart:253:10)
flutter: #61     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ═══════════════════════════════════════════════════════════════════════════════

**Comment by codegrue** [comment]
Fixed in 1.7.3

**Comment by gustavomesquita** [comment]
Thanks man!
